### ISSUE TITLE
How to login Balloons.IO with local user? Log up like omniauth-identity

### ISSUE THREAD

**Issue by sailorhero** [rickyrauch/Balloons.IO#80]

**Comment by johnhw1994** [comment]
I was able to get Facebook Authentication working but am getting issues with Twitter, if I log in with Twitter, it will direct me to Twitter page to allow my twitter app to authorize it, one I click sign in, it gives me an error saying : failed to find request token in session at Strategy.OAuthStrategy.authenticate.
